{
  "openapi": "3.0.0",
  "info": {
    "title": "Standalone - Notification Storage",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://wso2.extsrv.com/api/notifications",
      "variables": {}
    }
  ],
  "paths": {
    "/create/DEALING_MESSAGE": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "/create/DEALING_MESSAGE",
        "operationId": "/create/DEALING_MESSAGE",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1create~1DEALING_MESSAGE_Request"
              },
              "example": {
                "type": "dealing-message",
                "cid": "mk10016333",
                "dealingMessage": {
                  "localizableMessage": {
                    "key": "message_placed_sell_limit",
                    "parameters": [
                      "598096475",
                      "1000.0",
                      "EUR/AUD",
                      "1.62730",
                      "FOK",
                      "FOREX",
                      "598024573"
                    ]
                  },
                  "category": "TRADE_LOG",
                  "actionType": "ORDER_PLACED",
                  "critical": false,
                  "timeStamp": 1591186384892,
                  "reasonParameters": null,
                  "reasonKey": null
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/list/DEALING_MESSAGE/mk10016333": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "/list/DEALING_MESSAGE/{customerId}",
        "operationId": "/list/DEALING_MESSAGE/{customerId}",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/count/DEALING_MESSAGE/mk10016333": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "/count/DEALING_MESSAGE/{customerId}",
        "operationId": "/count/DEALING_MESSAGE/{customerId}",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/read/DEALING_MESSAGE": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/read/DEALING_MESSAGE",
        "operationId": "/update/read/DEALING_MESSAGE",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1read~1DEALING_MESSAGE_Request"
              },
              "example": {
                "messageIds": [
                  "9b71159c-22b8-4028-9276-5a959a855652"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/unread/DEALING_MESSAGE": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/unread/DEALING_MESSAGE",
        "operationId": "/update/unread/DEALING_MESSAGE",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1unread~1DEALING_MESSAGE_Request"
              },
              "example": {
                "messageIds": [
                  "9b71159c-22b8-4028-9276-5a959a855652"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/remove/DEALING_MESSAGE": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/remove/DEALING_MESSAGE",
        "operationId": "/update/remove/DEALING_MESSAGE",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1remove~1DEALING_MESSAGE_Request"
              },
              "example": {
                "messageIds": [
                  "9b71159c-22b8-4028-9276-5a959a855652"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/create/INFORM_MESSAGE": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "/create/INFORM_MESSAGE",
        "operationId": "/create/INFORM_MESSAGE",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1create~1INFORM_MESSAGE_Request"
              },
              "example": {
                "campaignName": "API3",
                "englishAsDefault": true,
                "texts": {
                  "en": {
                    "title": "Title-en API3",
                    "body": "Body-en API3",
                    "buttonText": "Button text-en API3"
                  },
                  "fr": {
                    "title": "Title-fr",
                    "body": "Body-fr",
                    "buttonText": "Button_text-fr"
                  }
                },
                "image": [
                  {
                    "_id": "5ebe52b620caf91ee7f3e4b7",
                    "imageTitle": "Image 1",
                    "imageUrl": "https://s3.eu-west-1.amazonaws.com/content-qa.extsrv.com/inform/1589531267267.jpg",
                    "originalFileName": "placeimg_640_480_tech1589531256693.jpg"
                  },
                  {
                    "_id": "5ece5603c397110b663d0ea0",
                    "imageTitle": "Image 2",
                    "imageUrl": "https://vamos-qa-platform-messaging.s3.eu-west-1.amazonaws.com/pictures/1590580691169.jpg",
                    "originalFileName": "1008_0167mol_7690_6hi1590580693109.jpg"
                  }
                ],
                "action": {
                  "id": "openTradingTool",
                  "instrument": null,
                  "url": "ui:price-alerts"
                },
                "tags": [
                  "Alert",
                  "New Feature"
                ],
                "customerIds": [
                  "mk10016333"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/list/NOTIFICATION_CENTER/mk10016333": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "/list/NOTIFICATION_CENTER_MESSAGE/{customerId}",
        "operationId": "/list/NOTIFICATION_CENTER_MESSAGE/{customerId}",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/count/NOTIFICATION_CENTER/mk10016333": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "/list/NOTIFICATION_CENTER_MESSAGE/{customerId}1",
        "operationId": "/list/NOTIFICATION_CENTER_MESSAGE/{customerId}1",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/read/NOTIFICATION_CENTER": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/read/NOTIFICATION_CENTER",
        "operationId": "/update/read/NOTIFICATION_CENTER",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1read~1NOTIFICATION_CENTER_Request"
              },
              "example": {
                "messageIds": [
                  "fb970faa-73ae-470a-bb13-39a715bd1d4a"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/unread/NOTIFICATION_CENTER": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/unread/NOTIFICATION_CENTER",
        "operationId": "/update/unread/NOTIFICATION_CENTER",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1unread~1NOTIFICATION_CENTER_Request"
              },
              "example": {
                "messageIds": [
                  "fb970faa-73ae-470a-bb13-39a715bd1d4a"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/update/remove/NOTIFICATION_CENTER": {
      "put": {
        "tags": [
          "Misc"
        ],
        "summary": "/update/remove/NOTIFICATION_CENTER",
        "operationId": "/update/remove/NOTIFICATION_CENTER",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/~1update~1remove~1NOTIFICATION_CENTER_Request"
              },
              "example": {
                "messageIds": [
                  ""
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "/create/DEALING_MESSAGE_Request": {
        "title": "/create/DEALING_MESSAGE_Request",
        "required": [
          "type",
          "cid",
          "dealingMessage"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "cid": {
            "type": "string"
          },
          "dealingMessage": {
            "$ref": "#/components/schemas/DealingMessage"
          }
        },
        "example": {
          "type": "dealing-message",
          "cid": "mk10016333",
          "dealingMessage": {
            "localizableMessage": {
              "key": "message_placed_sell_limit",
              "parameters": [
                "598096475",
                "1000.0",
                "EUR/AUD",
                "1.62730",
                "FOK",
                "FOREX",
                "598024573"
              ]
            },
            "category": "TRADE_LOG",
            "actionType": "ORDER_PLACED",
            "critical": false,
            "timeStamp": 1591186384892,
            "reasonParameters": null,
            "reasonKey": null
          }
        }
      },
      "DealingMessage": {
        "title": "DealingMessage",
        "required": [
          "localizableMessage",
          "category",
          "actionType",
          "critical",
          "timeStamp",
          "reasonParameters",
          "reasonKey"
        ],
        "type": "object",
        "properties": {
          "localizableMessage": {
            "$ref": "#/components/schemas/LocalizableMessage"
          },
          "category": {
            "type": "string"
          },
          "actionType": {
            "type": "string"
          },
          "critical": {
            "type": "boolean"
          },
          "timeStamp": {
            "type": "integer",
            "format": "int64"
          },
          "reasonParameters": {
            "type": "string",
            "nullable": true
          },
          "reasonKey": {
            "type": "string",
            "nullable": true
          }
        },
        "example": {
          "localizableMessage": {
            "key": "message_placed_sell_limit",
            "parameters": [
              "598096475",
              "1000.0",
              "EUR/AUD",
              "1.62730",
              "FOK",
              "FOREX",
              "598024573"
            ]
          },
          "category": "TRADE_LOG",
          "actionType": "ORDER_PLACED",
          "critical": false,
          "timeStamp": 1591186384892,
          "reasonParameters": null,
          "reasonKey": null
        }
      },
      "LocalizableMessage": {
        "title": "LocalizableMessage",
        "required": [
          "key",
          "parameters"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "parameters": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "key": "message_placed_sell_limit",
          "parameters": [
            "598096475",
            "1000.0",
            "EUR/AUD",
            "1.62730",
            "FOK",
            "FOREX",
            "598024573"
          ]
        }
      },
      "/update/read/DEALING_MESSAGE_Request": {
        "title": "/update/read/DEALING_MESSAGE_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            "9b71159c-22b8-4028-9276-5a959a855652"
          ]
        }
      },
      "/update/unread/DEALING_MESSAGE_Request": {
        "title": "/update/unread/DEALING_MESSAGE_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            "9b71159c-22b8-4028-9276-5a959a855652"
          ]
        }
      },
      "/update/remove/DEALING_MESSAGE_Request": {
        "title": "/update/remove/DEALING_MESSAGE_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            "9b71159c-22b8-4028-9276-5a959a855652"
          ]
        }
      },
      "/create/INFORM_MESSAGE_Request": {
        "title": "/create/INFORM_MESSAGE_Request",
        "required": [
          "campaignName",
          "englishAsDefault",
          "texts",
          "image",
          "action",
          "tags",
          "customerIds"
        ],
        "type": "object",
        "properties": {
          "campaignName": {
            "type": "string"
          },
          "englishAsDefault": {
            "type": "boolean"
          },
          "texts": {
            "$ref": "#/components/schemas/Texts"
          },
          "image": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Image"
            },
            "description": ""
          },
          "action": {
            "$ref": "#/components/schemas/Action"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "customerIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "campaignName": "API3",
          "englishAsDefault": true,
          "texts": {
            "en": {
              "title": "Title-en API3",
              "body": "Body-en API3",
              "buttonText": "Button text-en API3"
            },
            "fr": {
              "title": "Title-fr",
              "body": "Body-fr",
              "buttonText": "Button_text-fr"
            }
          },
          "image": [
            {
              "_id": "5ebe52b620caf91ee7f3e4b7",
              "imageTitle": "Image 1",
              "imageUrl": "https://s3.eu-west-1.amazonaws.com/content-qa.extsrv.com/inform/1589531267267.jpg",
              "originalFileName": "placeimg_640_480_tech1589531256693.jpg"
            },
            {
              "_id": "5ece5603c397110b663d0ea0",
              "imageTitle": "Image 2",
              "imageUrl": "https://vamos-qa-platform-messaging.s3.eu-west-1.amazonaws.com/pictures/1590580691169.jpg",
              "originalFileName": "1008_0167mol_7690_6hi1590580693109.jpg"
            }
          ],
          "action": {
            "id": "openTradingTool",
            "instrument": null,
            "url": "ui:price-alerts"
          },
          "tags": [
            "Alert",
            "New Feature"
          ],
          "customerIds": [
            "mk10016333"
          ]
        }
      },
      "Texts": {
        "title": "Texts",
        "required": [
          "en",
          "fr"
        ],
        "type": "object",
        "properties": {
          "en": {
            "$ref": "#/components/schemas/En"
          },
          "fr": {
            "$ref": "#/components/schemas/Fr"
          }
        },
        "example": {
          "en": {
            "title": "Title-en API3",
            "body": "Body-en API3",
            "buttonText": "Button text-en API3"
          },
          "fr": {
            "title": "Title-fr",
            "body": "Body-fr",
            "buttonText": "Button_text-fr"
          }
        }
      },
      "En": {
        "title": "En",
        "required": [
          "title",
          "body",
          "buttonText"
        ],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "buttonText": {
            "type": "string"
          }
        },
        "example": {
          "title": "Title-en API3",
          "body": "Body-en API3",
          "buttonText": "Button text-en API3"
        }
      },
      "Fr": {
        "title": "Fr",
        "required": [
          "title",
          "body",
          "buttonText"
        ],
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "buttonText": {
            "type": "string"
          }
        },
        "example": {
          "title": "Title-fr",
          "body": "Body-fr",
          "buttonText": "Button_text-fr"
        }
      },
      "Image": {
        "title": "Image",
        "required": [
          "_id",
          "imageTitle",
          "imageUrl",
          "originalFileName"
        ],
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "imageTitle": {
            "type": "string"
          },
          "imageUrl": {
            "type": "string"
          },
          "originalFileName": {
            "type": "string"
          }
        },
        "example": {
          "_id": "5ebe52b620caf91ee7f3e4b7",
          "imageTitle": "Image 1",
          "imageUrl": "https://s3.eu-west-1.amazonaws.com/content-qa.extsrv.com/inform/1589531267267.jpg",
          "originalFileName": "placeimg_640_480_tech1589531256693.jpg"
        }
      },
      "Action": {
        "title": "Action",
        "required": [
          "id",
          "instrument",
          "url"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "instrument": {
            "type": "string",
            "nullable": true
          },
          "url": {
            "type": "string"
          }
        },
        "example": {
          "id": "openTradingTool",
          "instrument": null,
          "url": "ui:price-alerts"
        }
      },
      "/update/read/NOTIFICATION_CENTER_Request": {
        "title": "/update/read/NOTIFICATION_CENTER_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            "fb970faa-73ae-470a-bb13-39a715bd1d4a"
          ]
        }
      },
      "/update/unread/NOTIFICATION_CENTER_Request": {
        "title": "/update/unread/NOTIFICATION_CENTER_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            "fb970faa-73ae-470a-bb13-39a715bd1d4a"
          ]
        }
      },
      "/update/remove/NOTIFICATION_CENTER_Request": {
        "title": "/update/remove/NOTIFICATION_CENTER_Request",
        "required": [
          "messageIds"
        ],
        "type": "object",
        "properties": {
          "messageIds": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "messageIds": [
            ""
          ]
        }
      }
    },
    "securitySchemes": {
      "httpBearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "httpBearer": []
    }
  ],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}